### Sign up
POST http://localhost:3001/api/v1/shop/signup
x-api-key: f72021dd595734a317e3dbaf349981bdecd23c208d67b41cca33c76e3835466f6e2db0f4dd7dfcc44c40bbd75c6dfa69ecd1977ccf5e75b64e85cbcf65e2b322
content-type: application/json

{
    "name": "7",
    "email": "7@gmail.com",
    "password": "1234156"
}

### Login
POST http://localhost:3001/api/v1/shop/login
x-api-key: f72021dd595734a317e3dbaf349981bdecd23c208d67b41cca33c76e3835466f6e2db0f4dd7dfcc44c40bbd75c6dfa69ecd1977ccf5e75b64e85cbcf65e2b322
content-type: application/json

{
    "email": "3@gmail.com",
    "password": "1234156"
}

### logout
POST http://localhost:3001/api/v1/shop/logout
x-api-key : f72021dd595734a317e3dbaf349981bdecd23c208d67b41cca33c76e3835466f6e2db0f4dd7dfcc44c40bbd75c6dfa69ecd1977ccf5e75b64e85cbcf65e2b322
x-client-id : 6667b6484aa00049c98e42c0
authorization : eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJzaG9wSWQiOiI2NjY3YjY0ODRhYTAwMDQ5Yzk4ZTQyYzAiLCJlbWFpbCI6IjRAZ21haWwuY29tIiwiaWF0IjoxNzE4MDcyOTk0LCJleHAiOjE3MTkyODI1OTR9.fAIkPEf3IVInBzBBNBrLOXiqsfgB5HoY6y4Zn8P_NzJNE0gSaACYsF4mcz1trcmo5m8tbbCEj4xzVEau2xZeqg9qx4FBrvPwszCpGNJw0jQ8XKaeYEBIsHRoL3E9uXWW-u84OHDLvbqYGDpfGe66LzAQswHtLqf30VO9fIXN2fcl3PhMrn42LgWODdBvYQlFr9NXbgI3jRXijm_Nk8OuRTdQyD9NORJYB6IRYAEeHSQLdD9bTLurLL8YG2DMny-VVSlNusO4-oR93KD89bXRK-tMo2l2SyBxijHFqbyx74Htn7i8f6XCdpY6MFKf69V-W5MwAdAj_p8E6Kj3cM3oaZgGfRAfZQcdRlRGLHtSJZrUY7nuMw9sECff-dCp2YHuhvPRY0Pz2Zz0xE4W0_79U9pX90zot-GW5iZPSZN4Gq2yzPBO2uVnhnbe_VDerrQt-vOzub9vNNB0-M2MxjRr9cr40dk4ofjR4ZpzNFep0xgSS4jAFfGTv3bZ14UfVMgxhV7ACC9KOHYNID0Ul-G21baO6HtM4CL8CXA9AlaFrrxr8_kJHwPQ8fhE3uHiv_2vdaiU41GsO1A9KJZhsV60rN_1OHuwg2ZXaJZasntxK0JfCc6y6mQO06sIesGoe_z5qftHGelpE-NO0zR2uQ3D4aFkebGWlit0xrO9DZlq5oo


### handle refresh token
POST http://localhost:3001/api/v1/shop/refresh-token
x-api-key : f72021dd595734a317e3dbaf349981bdecd23c208d67b41cca33c76e3835466f6e2db0f4dd7dfcc44c40bbd75c6dfa69ecd1977ccf5e75b64e85cbcf65e2b322
x-client-id : 6667c81cee3cae051e38b0d1
authorization : eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJzaG9wSWQiOiI2NjY3YzgxY2VlM2NhZTA1MWUzOGIwZDEiLCJlbWFpbCI6IjNAZ21haWwuY29tIiwiaWF0IjoxNzE4MDc3OTgwLCJleHAiOjE3MTgxNjQzODB9.6imCNDuxlKqMHItcMOFb5ZzFhisay3KhfrncU7KnS0Sdnv0vnCB7pFNPKP5spfQ_ppvhkIvhED1VGnDT1ZLRlXxSR3ypXJ4zoppcEp9gFPHpQYhoEWLByn8LOKwVYpDQ2rike_YgD3MpKygNa1J8JKRJ74P7mGqvFeod6hb0V_uz1QQ3Umham6eNV1WaRcztfnHTdrm4HGVoqZ-V6EDUVm5ae_Zmu1_Hmd7PRkZ9bcqd_w70hG0Td81osPC3PAKTx1Bwaelz4GiZUnayAMOClgwC-N7GmrclGAovau6Bq8PHYlxGMgIGvAsbazVJ8XauAiCl1xb8m_z40AuHizq8FhVm545twCFGe2GygA6rnbkMn8L2fPj5IPHvu6vpDl9OjaluwLb0OGKfpuKqGM1o7R0yYCRfEpwVQvG9Q7h--qMQRloIT9dJ8VNhxNH9XGvvSaBzgI9vn_jZ6WP8010dCLxopve3zgzBMu8jWciACCr13Q3_y6-qUsSJJTdd1Jzxxs0Chy5R6axuL2iovHo3w0bk2DxAzeEcNXx9VKvhkYMwM1N3DSDyGQMmN8OTQDYhVmwi_s9I4p2iTJGjOd5UIG9oUokqZsmIO2m0kk8JcQi72Qht_846-G3YImC2uRoVn-CDW23P7yGMOFba0eyvYitg5oOueOexuWl75FndAkc
content-type: application/json

{
"refreshToken": "eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJzaG9wSWQiOiI2NjY3YzgxY2VlM2NhZTA1MWUzOGIwZDEiLCJlbWFpbCI6IjNAZ21haWwuY29tIiwiaWF0IjoxNzE4MDc3OTgwLCJleHAiOjE3MTkyODc1ODB9.08d_Lhl49xiWFDBozdVGzqURMEWwP0MlAIoq0AbZAhFD9D0Wbtv1DwrvA18sBswG9hljMvOrBJrygVxtatsIQOUJA23ZvWAukF_0mSKSEeqtBZOZmMeYnEo1GIkFAEZ6eoMXOdfRyOUL8GgooBSsbq8aMpPO0xJeppxYVFtEEiRqtcyAu0WiaP4GL7RQUMTkH09lNQ5Aro6fSQ2XgVERZDCTUOEqp_oGqcGh8A23Cta-PoomKUAHRLRj7rx9AgDgZR9YJxnpBxZ03p8mpHfKViitv8fovDyEJhJCo1umgUCQTHkDmhM57q_jdjYRN8a6YpuSAia0iK26DD6LEjHyWM3Hf7N1Y66OfuTI88ElodXEa4UJECRSUuEbFW9hG1TPhl9MZGEQTwp9ltPTWVwBR07DurElFyzgoOXi57eM6mUXvOGB0w0JFpF8k_KnsTE6dDvKglUj97s_FPQ1Qkj-id661wgE1SNT6Iy10H5i2RICbgQPnZe0lv96bMus15zcbQ7h-5oPn01vGNq5Y4sUQxE6ZmMz_vgxIamI245CtoXB4ED1Eprwr7cHWeK9h36GLR8vqkvoXVYsFSpz3iODzK9EWrzRWDdhNZGB8J48A2j_TKCKuxPKwXIgsc4sIxxciaqVNKvLSpWEQsxPhGBYEYwXZ2n7Gi19dRsZHQ2y16Q"}