@ACCESSTOKEN = eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NjdhNjcxMjVjNzY0YzA4YWQ3NzU4ZWEiLCJlbWFpbCI6IjdAZ21haWwuY29tIiwiaWF0IjoxNzE5NDYwMzM4LCJleHAiOjE3MTk1NDY3Mzh9.ltl4uuV_lOk2VE3ol0PJJ7b93Zp7ziy4mffv8-WVOftOUlPWQakVDEaAwxe20rJ_jvR88V3ZhBSCQ-7-zNm9bvKqvu0CzkS-9ZaFoNCvOnoaDp0NKsRYTh7rq96w0UeBcwHvwlUKcy-LoYPnCYzcWmzrCjiI8krpWM5aC5DErCCM6uHMXE3cYMOUVn7Lte2SHXZtOAnuAt0LY-Nj7okuKiUuThVcQfUOY2-qvmdZKUNXRVXLPJ8-TRN21-LfuZd0puEYJ0vf37yHJpMiDj1M4vznECNnWmiwPLmXCLxoZsF79dBf14CgL_jXFFLPvXihzC0t3aLPgox9R7fBj3q52QdnKhAm7PHyOmrFt4tobiov0KDQWyAKHFocmnscivw1zWeQMeZteMht53I0MxWHwTyEiNhhnAltcPzWfCNRyru8Bht5g6_gKdhePug5R2prVFZB-Hl-6KaaKVPu9BZfgelKCJ1qMWHpjco2ULY9YKfrCg3atdNXoz4D1VjsXcu6CC0AM4Ga9tXyzr-evfKbqvSa3qmK4F9VIxwVPoDvczu5_6LPnb8leR8tY0e11HIVnNnvT-brR6MGqvVrb1Dd7cqbAdt0pie8hiaTCol1skHj5s_V47YGQzAyAEi2b1RVJldbqC0bdvVVuA5s3hiuM7E6392jF80rUjDK7wzuFCg
@REFRESHTOKEN = eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NjdhNjcxMjVjNzY0YzA4YWQ3NzU4ZWEiLCJlbWFpbCI6IjdAZ21haWwuY29tIiwiaWF0IjoxNzE5NDYwMzM4LCJleHAiOjE3MjA2Njk5Mzh9.H1qmc7i1c5pNqm2RZVSL9Z7PCwd8enrAe0wyrFRHwEvmxkDgn4fOti_I33K9VNAtbM8lJcoyxQWG-6gG9U_jwq8PhhXAdSuDFf-CXV8L5tc9CDMSQYhsJ97OiA-MBmm6s4wTEi0ba3lxMqkcN5ASybkAUZWQtOdNOyQSZHbBXl5YWig7Ec0APWgiyI1qL61MZBQ1aPreZI6o2Kkdob5Yjyt5XPrDvTXjQmR22bIso9j0cOL_-_CA8QIOeEUqnqsM3Vmb78QIrw2iRfw5Zn_A0gqv2xE0BNdBeBOFy-Gp5E9IHYMKIe5CG745NeaijyPvpV6FNM8ZOszRnWgUsACWU_H46aFN9xxXI69iDuOlOKznUnby6aObXrqpDK-BveE6hL_chFNYiObor6VM-JqmYR7IGwNnvr4jwspFs_V8rk2i2_6zCMTL0KuxvfNHQdTC3IHnpZ-cQ_mxvnHBqdPEGWvsYG4SvAYFVfuby5J660F6yLjTGO3ADoJNroKdAVvz9a_JcYaHtoHJvMPVgAlPoZSw7QqVzYjbmfLORp-Lg9mLTwZ33RKhDkUcbf17EZvx8AW72RQ4Tip3qioYF44z_gVFEatonNCZGaAUxlisAbO-WQgQBkhvAlbdQpoV_JK6O49aWXVgPr2NQ5njugPz_llojlYGhhR3L4PP-_aWSr8
@APIKEY = fffbff1907f9fd6c85428a77850851fcdb791963dc660f341d04d7829507e08efcb63ba8037b4e8c6f967e1e5dab3ae81cde008fb88969c0cd18a66a54df8cec

@SHOPID = 667a67125c764c08ad7758ea
### Sign up
x-api-key: {{APIKEY}}
content-type: application/json

{
    "name": "7",
    "email": "7@gmail.com",
    "password": "1234156"
}

### Login
POST http://localhost:3001/api/v1/shop/login
x-api-key: {{APIKEY}}
content-type: application/json

{
    "email": "7@gmail.com",
    "password": "1234156"
}

### logout
POST http://localhost:3001/api/v1/shop/logout
x-api-key : {{APIKEY}}
x-client-id : {{SHOPID}}
authorization : eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJzaG9wSWQiOiI2NjY3YjY0ODRhYTAwMDQ5Yzk4ZTQyYzAiLCJlbWFpbCI6IjRAZ21haWwuY29tIiwiaWF0IjoxNzE4MDcyOTk0LCJleHAiOjE3MTkyODI1OTR9.fAIkPEf3IVInBzBBNBrLOXiqsfgB5HoY6y4Zn8P_NzJNE0gSaACYsF4mcz1trcmo5m8tbbCEj4xzVEau2xZeqg9qx4FBrvPwszCpGNJw0jQ8XKaeYEBIsHRoL3E9uXWW-u84OHDLvbqYGDpfGe66LzAQswHtLqf30VO9fIXN2fcl3PhMrn42LgWODdBvYQlFr9NXbgI3jRXijm_Nk8OuRTdQyD9NORJYB6IRYAEeHSQLdD9bTLurLL8YG2DMny-VVSlNusO4-oR93KD89bXRK-tMo2l2SyBxijHFqbyx74Htn7i8f6XCdpY6MFKf69V-W5MwAdAj_p8E6Kj3cM3oaZgGfRAfZQcdRlRGLHtSJZrUY7nuMw9sECff-dCp2YHuhvPRY0Pz2Zz0xE4W0_79U9pX90zot-GW5iZPSZN4Gq2yzPBO2uVnhnbe_VDerrQt-vOzub9vNNB0-M2MxjRr9cr40dk4ofjR4ZpzNFep0xgSS4jAFfGTv3bZ14UfVMgxhV7ACC9KOHYNID0Ul-G21baO6HtM4CL8CXA9AlaFrrxr8_kJHwPQ8fhE3uHiv_2vdaiU41GsO1A9KJZhsV60rN_1OHuwg2ZXaJZasntxK0JfCc6y6mQO06sIesGoe_z5qftHGelpE-NO0zR2uQ3D4aFkebGWlit0xrO9DZlq5oo


### handle refresh token
POST http://localhost:3001/api/v1/shop/refresh-token
x-api-key : {{APIKEY}}
x-client-id : {{SHOPID}}
authorization : {{ACCESSTOKEN}}
content-type: application/json

{
"refreshToken": "{{REFRESHTOKEN}}"
}