@ACCESSTOKEN = eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NjdhNjcxMjVjNzY0YzA4YWQ3NzU4ZWEiLCJlbWFpbCI6IjdAZ21haWwuY29tIiwiaWF0IjoxNzIwMDgzMjExLCJleHAiOjE3MjAxNjk2MTF9.KLRbnfyFTXcSm3cqZykL1fEvPqLzIifruiEOQc5iSLGfz3z2U30kUwY2wiV3gnqgfXZQ5IYw9f_R5muRuuPJUEDAntmBX2SX6J2jcugs7yBR0bKS2MYv_xlqutI4wvdXQvnKmpzbVyJOZRWQI3cRrgielMNhulbZ2tGB7v18INkZAu188dqj82WgUIxPPdkcW3dgygGf0mXSJRu4x-1JXQjYGnMB39scY27BliqJ4qjL8Z7FrLCmhjPCXDrySomHP9_b94Jcp_4zJdI_y1ut0t3hMWXT-Hm46tHxIncvjCk-CwX-zzvsJXXuT2XbqMSCb78f2BvlchooKmv0lC56gqxZI4SNk747A31GGjxSYG6o5XtiO_FJhEtKBhzsuNU1h2509SR9h1rPUMdX1vcUMedNY-2Qgd2felN9907FRG2GmFUp0GotciOQ2SnCrShCyvxsMY_ET_HUuvw92xWTG_ssSMOJ6NY088klhUx6EX77Wh9OLp68_KGMua9m-_ScounkgoGNJv0lku8fLYWC21fIq5COUDK-2IIlTSLM4jtUZif927dNqosWsuJYG2iwHRflSi-G1AkubanAIunNPkAtFoW8z-CD3Bea8_ZpKB6BwP4E8KSxMron6lgMYkv_lR4X47GyLjs7KEXD6nKrp2e5dRZVSMZ5EgC7KhUKoxY

@REFRESHTOKEN = eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NjdhNjcxMjVjNzY0YzA4YWQ3NzU4ZWEiLCJlbWFpbCI6IjdAZ21haWwuY29tIiwiaWF0IjoxNzIwMDgzMjExLCJleHAiOjE3MjEyOTI4MTF9.m5L94aAvkIZFPMgqOoU6LkWVQ7wcWD1gR4bfEsCUSAmwfjQ9Nw53uiZ1RsoCPcJjHOKr43TOyTs6KlLs2q117f--fgwPyTkJXSnuIijPuAGwBlnahuUYSF8JRJ0fYuIv6XPtDcaWt6h3PMKuzEq32NWbOy5yMDBzK3f4PsDkgCs0t8ALOIJi7bpD_oftL57m8U4wPJO-nKe9XhzrNb1zJxnq_8N_-gjhEc7_uvuDeNL0ye9B0YT8PaBrBxE8AWeDeO2_gsTlpMTD2m4s7i0pMFPnUgSx_VlM6YP3VOMexuyBn_6bBM-evwcEKZBmb6SX0jLZ5fceqqDTlhGxrbiFRPJfMw06d8HVxkLXnFcR3Li7WMfY6bcFEDa1sT2uMlSUJx_UpzV49MPD2V8RLDR-nQPvzrdrgVxl_7KhuMPdyU7hkuYTRca1uWuRi6JKDNy7v6IKB-osmlYyM861WPkBQytPLeinKLWgKg1jgdeZikVg573K-YdMfC5LVof0eR1cFOhkPM61mrhP7SanOMLjOdKFI2WWai37O3uhTDzttnwBpDO8SnmepBcbluMx9JKvvShWARYuxOJjRnlRS4m0OBF7vZoKMt8URDZiHzh3UzITbpqLRcQuEu9lb9Auuc364ed3U587GEHf3KZi5Moubz2jJRhl53xX7Diwqodv_f4

@APIKEY = fffbff1907f9fd6c85428a77850851fcdb791963dc660f341d04d7829507e08efcb63ba8037b4e8c6f967e1e5dab3ae81cde008fb88969c0cd18a66a54df8cec

@SHOPID = 667a67125c764c08ad7758ea
### Sign up
x-api-key: {{APIKEY}}
content-type: application/json

{
    "name": "7",
    "email": "7@gmail.com",
    "password": "1234156"
}

### Login
POST http://localhost:3001/api/v1/shop/login
x-api-key: {{APIKEY}}
content-type: application/json

{
    "email": "7@gmail.com",
    "password": "1234156"
}

### logout
POST http://localhost:3001/api/v1/shop/logout
x-api-key : {{APIKEY}}
x-client-id : {{SHOPID}}
authorization : eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJzaG9wSWQiOiI2NjY3YjY0ODRhYTAwMDQ5Yzk4ZTQyYzAiLCJlbWFpbCI6IjRAZ21haWwuY29tIiwiaWF0IjoxNzE4MDcyOTk0LCJleHAiOjE3MTkyODI1OTR9.fAIkPEf3IVInBzBBNBrLOXiqsfgB5HoY6y4Zn8P_NzJNE0gSaACYsF4mcz1trcmo5m8tbbCEj4xzVEau2xZeqg9qx4FBrvPwszCpGNJw0jQ8XKaeYEBIsHRoL3E9uXWW-u84OHDLvbqYGDpfGe66LzAQswHtLqf30VO9fIXN2fcl3PhMrn42LgWODdBvYQlFr9NXbgI3jRXijm_Nk8OuRTdQyD9NORJYB6IRYAEeHSQLdD9bTLurLL8YG2DMny-VVSlNusO4-oR93KD89bXRK-tMo2l2SyBxijHFqbyx74Htn7i8f6XCdpY6MFKf69V-W5MwAdAj_p8E6Kj3cM3oaZgGfRAfZQcdRlRGLHtSJZrUY7nuMw9sECff-dCp2YHuhvPRY0Pz2Zz0xE4W0_79U9pX90zot-GW5iZPSZN4Gq2yzPBO2uVnhnbe_VDerrQt-vOzub9vNNB0-M2MxjRr9cr40dk4ofjR4ZpzNFep0xgSS4jAFfGTv3bZ14UfVMgxhV7ACC9KOHYNID0Ul-G21baO6HtM4CL8CXA9AlaFrrxr8_kJHwPQ8fhE3uHiv_2vdaiU41GsO1A9KJZhsV60rN_1OHuwg2ZXaJZasntxK0JfCc6y6mQO06sIesGoe_z5qftHGelpE-NO0zR2uQ3D4aFkebGWlit0xrO9DZlq5oo


### handle refresh token
POST http://localhost:3001/api/v1/shop/refresh-token
x-api-key : {{APIKEY}}
x-client-id : {{SHOPID}}
authorization : {{ACCESSTOKEN}}
content-type: application/json

{
"refreshToken": "{{REFRESHTOKEN}}"
}

### create product
POST http://localhost:3001/api/v1/product
x-api-key : {{APIKEY}}
x-client-id : {{SHOPID}}
authorization : {{ACCESSTOKEN}}
content-type: application/json

{
  "product_name": "Nike Air Max 99",
  "product_thumbnail": "https://example.com/airmax90.jpg",
  "product_shop": "{{SHOPID}}",
  "product_price": 120.00,
  "product_quantity": 35,
  "product_type": "clothes",
  "product_description": "Iconic running shoes with classic design.",
  "product_attributes": {
    "size": "US 9",
    "color": "Black/White",
    "material": "Leather/Mesh",
    "brand": "Nike"
  }
}

### get shop draft products
GET http://localhost:3001/api/v1/product/draft/all
x-api-key : {{APIKEY}}
x-client-id : {{SHOPID}}
authorization : {{ACCESSTOKEN}}

### publish product by id
POST http://localhost:3001/api/v1/product/published/66842e21a162a09f714d84b1
x-api-key : {{APIKEY}}
x-client-id : {{SHOPID}}
authorization : {{ACCESSTOKEN}}

### unpublish product by id
POST http://localhost:3001/api/v1/product/unpublished/66842e21a162a09f714d84b1
x-api-key : {{APIKEY}}
x-client-id : {{SHOPID}}
authorization : {{ACCESSTOKEN}}



### get shop published products
GET http://localhost:3001/api/v1/product/published/all
x-api-key : {{APIKEY}}
x-client-id : {{SHOPID}}
authorization : {{ACCESSTOKEN}}

### search product by name,discription
GET http://localhost:3001/api/v1/product/search/nike 90
x-api-key : {{APIKEY}}

### get product by id
GET http://localhost:3001/api/v1/product/66842e21a162a09f714d84b1
x-api-key : {{APIKEY}}

### get all products
GET http://localhost:3001/api/v1/product/all
x-api-key : {{APIKEY}}

### update product by id
PATCH http://localhost:3001/api/v1/product/66842e21a162a09f714d84b1
x-api-key : {{APIKEY}}
x-client-id : {{SHOPID}}
authorization : {{ACCESSTOKEN}}
content-type: application/json

{
  "product_name": "Nike Air Max 9000",
  "product_type": "clothes",
  "product_attributes": {
    "size": "US 9"
  }
}
