@ACCESSTOKEN = eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NjdhNjZkODg0YmU4MzRiYWEyODk3YjkiLCJlbWFpbCI6IjFAZ21haWwuY29tIiwiaWF0IjoxNzIwNzA4MDQxLCJleHAiOjE3MjA3OTQ0NDF9.lJQl2lgK-9C0U625H_4ThwCBbBTLd9R5iLKi10lD-vH39YoYY4G0L5_MipVLioYyt6NhbPIDzUu11sNLwDubWc5u_coBD-KYoZKMWyaWkCljgr0s1txSkMkU8CNtjoa__5v_p2QMctIXSGkDYlOktFAQnRGIquzN_YIpWf5Doq8X1GaEWLOf1gQ5vi-m3Qvwed95-2V4pxEcvGm2Wki1OLkC5weZoC_uK2_d5qlIMZ49rXwtmecPsxB-814_STflTBwOwLZYQkNHt7-cm4M5Q7TIH56wgcHBd_O4rsKq09pBREoknDMPGXtI7zMd5O5o9c6XnHEQrc49LbaVRVJbCkzpNocYsVZ7gJi9w1HwKhUQB07PXgr6TEopbGQhNTqCBrqitTeIND-CLQJja3JbeEYTx2IPPeEPTSKkygQ8I41BeJOa8JsZauDKId4UqZdpRKD_Sa1IKa7N6qHjb0YZKuZNVB43hyd8nN-Dp9qoh4hCfxeI1XD0BCKCilbGi0-Ttvh6mlFJSlfKDuKxjyOjaS1lTT656rBLbNWkzbwvwsVrJaqQeoD3VIGq9LJyaS7mHWhYhh3QWrrtjILhHC_dBJ3MtzXsjbPqsGxMqvIDsxUhoIlDEc_SR3cqdXqljlmaqL2nLH3y4gbHNBqEAPkvepAcn-dhJbicPU3Y2U7HlNk
@REFRESHTOKEN = eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NjdhNjZkODg0YmU4MzRiYWEyODk3YjkiLCJlbWFpbCI6IjFAZ21haWwuY29tIiwiaWF0IjoxNzIwNzA4MDQxLCJleHAiOjE3MjE5MTc2NDF9.NTvoVnOPXP_JvEffXIJJ4JP5YRW-N759r_EnuIspu19WL7epoksVc_hSxZhfU77U3Wu6tIVpnqP3kcSJU1wxqCaIptypvew3T5YRs0e5s4mcyjgUXMIpqVJJMxGTjdgf80NI6Ilk7LJ5Bzw6o-naJKvZ-hKpZwDUgKQ3qCE5oad1bfBUOxz_4KEhK1ktyYOYe8WvwJlsUKBkGv4DbdNeCwMKyTD3lnXDuoCnlNTArBCGwbcsHXFzVC3ld1zeg6WKR8_A4gE_zR8dYnsiPgMXxTgAr1kmd94V_r3nDU4b4bBNUpw9C6fxP29RH7iATTpQ4pQDBx_bkdjpsVEhwrLJlhbElZK6AV1F9GvMe83hbnduTyWh_S3KhaBnDcwLvnIj--JHaAugfs6meCPOtIYytC2eKug8z3ZWUvGAlKbOgkSRh4vlCHan8CdY5qIhdyhmInWmr9pgfAKYX73C2NDyADT2sAiwRskb9C7j502Ga1QJX4y4jtLXCGDyKuxbzqjsw0mASpkl01IgadfeGsGqQ7FBTVaswGQFEL7v-cClvwzANUqojseH31yMeA4DteXUjVGhobHyc7ICEpQrTUAlC60XVnK1A1qXiM_BlNwyoMUeiFlOvaEC1fJp_-R3wUavB-g_7srjY8ANE7uiQUse-MecirmgMe04e2XHUE_wzsw
@APIKEY = fffbff1907f9fd6c85428a77850851fcdb791963dc660f341d04d7829507e08efcb63ba8037b4e8c6f967e1e5dab3ae81cde008fb88969c0cd18a66a54df8cec

@SHOPID = 667a67125c764c08ad7758ea

@SHOPID2 = 667a66d884be834baa2897b9

@PRODUCTID = 66891a418bddb3f5cb89fa8c

@PRODUCTID2 = 66891a628bddb3f5cb89fa94

@PRODUCTID3 = 66891a418bddb3f5cb89fa8c

@DISCOUNTCODE = Birth2024
### Sign up
x-api-key: {{APIKEY}}
content-type: application/json

{
    "name": "7",
    "email": "7@gmail.com",
    "password": "1234156"
}

### Login
POST http://localhost:3001/api/v1/shop/login
x-api-key: {{APIKEY}}
content-type: application/json

{
    "email": "1@gmail.com",
    "password": "1234156"
}

### logout
POST http://localhost:3001/api/v1/shop/logout
x-api-key : {{APIKEY}}
x-client-id : {{SHOPID}}
authorization : eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJzaG9wSWQiOiI2NjY3YjY0ODRhYTAwMDQ5Yzk4ZTQyYzAiLCJlbWFpbCI6IjRAZ21haWwuY29tIiwiaWF0IjoxNzE4MDcyOTk0LCJleHAiOjE3MTkyODI1OTR9.fAIkPEf3IVInBzBBNBrLOXiqsfgB5HoY6y4Zn8P_NzJNE0gSaACYsF4mcz1trcmo5m8tbbCEj4xzVEau2xZeqg9qx4FBrvPwszCpGNJw0jQ8XKaeYEBIsHRoL3E9uXWW-u84OHDLvbqYGDpfGe66LzAQswHtLqf30VO9fIXN2fcl3PhMrn42LgWODdBvYQlFr9NXbgI3jRXijm_Nk8OuRTdQyD9NORJYB6IRYAEeHSQLdD9bTLurLL8YG2DMny-VVSlNusO4-oR93KD89bXRK-tMo2l2SyBxijHFqbyx74Htn7i8f6XCdpY6MFKf69V-W5MwAdAj_p8E6Kj3cM3oaZgGfRAfZQcdRlRGLHtSJZrUY7nuMw9sECff-dCp2YHuhvPRY0Pz2Zz0xE4W0_79U9pX90zot-GW5iZPSZN4Gq2yzPBO2uVnhnbe_VDerrQt-vOzub9vNNB0-M2MxjRr9cr40dk4ofjR4ZpzNFep0xgSS4jAFfGTv3bZ14UfVMgxhV7ACC9KOHYNID0Ul-G21baO6HtM4CL8CXA9AlaFrrxr8_kJHwPQ8fhE3uHiv_2vdaiU41GsO1A9KJZhsV60rN_1OHuwg2ZXaJZasntxK0JfCc6y6mQO06sIesGoe_z5qftHGelpE-NO0zR2uQ3D4aFkebGWlit0xrO9DZlq5oo


### handle refresh token
POST http://localhost:3001/api/v1/shop/refresh-token
x-api-key : {{APIKEY}}
x-client-id : {{SHOPID}}
authorization : {{ACCESSTOKEN}}
content-type: application/json

{
"refreshToken": "{{REFRESHTOKEN}}"
}
### create product 
POST http://localhost:3001/api/v1/product
x-api-key : {{APIKEY}}
x-client-id : {{SHOPID}}
authorization : {{ACCESSTOKEN}}
content-type: application/json

{
  "product_name": "Gucci Bag 1",
  "product_thumbnail": "https://example.com/gucci-bag.jpg 1",
  "product_shop": "{{SHOPID}}",
  "product_price": 120.00,
  "product_quantity": 35,
  "product_type": "clothes",
  "product_description": "Gucci Bag 1",
  "product_attributes": {
    "size": "US 8",
    "color": "black",
    "material": "leather",
    "brand": "Gucci"
  }
}

### create product 2
POST http://localhost:3001/api/v1/product
x-api-key : {{APIKEY}}
x-client-id : {{SHOPID2}}
authorization : {{ACCESSTOKEN}}
content-type: application/json

{
  "product_name": "Nike Air Max 9000",
  "product_thumbnail": "https://example.com/nike-air-max-9000.jpg",
  "product_shop": "{{SHOPID2}}",
  "product_price": 120.00,
  "product_quantity": 35,
  "product_type": "clothes",
  "product_description": "Nike Air Max 9000",
  "product_attributes": {
    "size": "US 9",
    "color": "black",
    "material": "leather",
    "brand": "Nike"
  }
}

### create product 3
POST http://localhost:3001/api/v1/product
x-api-key : {{APIKEY}} 
x-client-id : {{SHOPID2}}
authorization : {{ACCESSTOKEN}}
Content-Type: application/json

{
  "product_name": "Jordan 1",
  "product_thumbnail": "https://example.com/jordan-1.jpg",
  "product_shop": "{{SHOPID2}}",
  "product_price": 120.00,
  "product_quantity": 35,
  "product_type": "clothes",
  "product_description": "Jordan 1",
  "product_attributes": {
    "size": "US 9",
    "color": "black",
    "material": "leather",
    "brand": "Jordan"
  }
}


### get shop draft products
GET http://localhost:3001/api/v1/product/draft/all
x-api-key : {{APIKEY}}
x-client-id : {{SHOPID}}
authorization : {{ACCESSTOKEN}}

### publish product by id
POST http://localhost:3001/api/v1/product/published/66842e21a162a09f714d84b1
x-api-key : {{APIKEY}}
x-client-id : {{SHOPID}}
authorization : {{ACCESSTOKEN}}

### unpublish product by id
POST http://localhost:3001/api/v1/product/unpublished/66842e21a162a09f714d84b1
x-api-key : {{APIKEY}}
x-client-id : {{SHOPID}}
authorization : {{ACCESSTOKEN}}



### get shop published products
GET http://localhost:3001/api/v1/product/published/all
x-api-key : {{APIKEY}}
x-client-id : {{SHOPID}}
authorization : {{ACCESSTOKEN}}

### search product by name,discription
GET http://localhost:3001/api/v1/product/search/nike 90
x-api-key : {{APIKEY}}

### get product by id
GET http://localhost:3001/api/v1/product/66842e21a162a09f714d84b1
x-api-key : {{APIKEY}}

### get all products
GET http://localhost:3001/api/v1/product/all
x-api-key : {{APIKEY}}

### update product by id
PATCH http://localhost:3001/api/v1/product/66842e21a162a09f714d84b1
x-api-key : {{APIKEY}}
x-client-id : {{SHOPID}}
authorization : {{ACCESSTOKEN}}
content-type: application/json

{
  "product_name": "Nike Air Max 9000",
  "product_type": "clothes",
  "product_attributes": {
    "size": "US 9"
  }
}

### create discount
POST http://localhost:3001/api/v1/discount/create
x-api-key : {{APIKEY}}
x-client-id : {{SHOPID2}}
authorization : {{ACCESSTOKEN}}
content-type: application/json

{
  "discount_name": "Birth Sale",
  "discount_code": "Birth2024",
  "discount_description": "Birth Sale 2024",
  "discount_shop": "{{SHOPID}}",
  "discount_type": "percentage",
  "discount_value": 20,
  "discount_apply_on": "products",
  "discount_product_ids": ["668fec8e052f68d2c7031245"],
  "discount_min_order_value": 100,
  "discount_max_usage": 100,
  "discount_start_date": "2024-07-01",
  "discount_end_date": "2024-07-31"
}

### update discount
PATCH  http://localhost:3001/api/v1/discount/Birth2024
x-api-key : {{APIKEY}}
x-client-id : {{SHOPID}}
authorization : {{ACCESSTOKEN}}
content-type: application/json

{
  "discount_name": "Birth Sale 2024",
  "discount_description": "Birth Sale 2024 Sieu Cap Vip Pro"
}

### get shop discounts
GET http://localhost:3001/api/v1/discount/all
x-api-key : {{APIKEY}}
x-client-id : {{SHOPID}}
authorization : {{ACCESSTOKEN}}

### get product by discount code id
GET http://localhost:3001/api/v1/discount/products
x-api-key : {{APIKEY}}
x-client-id : {{SHOPID}}
authorization : {{ACCESSTOKEN}}
content-type: application/json

{
  "discount_code": "Birth2024",
  "discount_shopId": "{{SHOPID}}"
}

### get amount order
GET http://localhost:3001/api/v1/discount/amount
x-api-key : {{APIKEY}}
x-client-id : {{SHOPID}}
authorization : {{ACCESSTOKEN}}
content-type: application/json

{
  "discount_code": "Birth2024",
  "discount_shopId": "{{SHOPID}}",
  "products": [
    {
      "product_id": "66891a628bddb3f5cb89fa94",
      "product_price": 120,
      "product_quantity": 2
    },
    {
      "product_id": "66891a628bddb3f5cb89fa94",
      "product_price": 120,
      "product_quantity": 1
    }
  ]
}

### add product to cart
POST http://localhost:3001/api/v1/cart/add
x-api-key : {{APIKEY}}
x-client-id : {{SHOPID2}}
authorization : {{ACCESSTOKEN}}
content-type: application/json

{"userId": "667", 
 "product": {
    "productId": "66891a418bddb3f5cb89fa8c",
    "product_price": 150,
    "product_quantity": 1,
    "product_name": "Nike Air Max 9000",
     "product_shopId ": "{{SHOPID}}"
  }
 }

### get cart by user id
GET http://localhost:3001/api/v1/cart/
x-api-key : {{APIKEY}}
x-client-id : {{SHOPID}}
authorization : {{ACCESSTOKEN}}
content-type: application/json

{"userId": "667"}

### update product in cart
PATCH http://localhost:3001/api/v1/cart/update
x-api-key : {{APIKEY}}
x-client-id : {{SHOPID}}
authorization : {{ACCESSTOKEN}}
content-type: application/json

{"userId": "667", 
 "product": {
    "productId": "66891a418bddb3f5cb89fa8c",
    "product_price": 150,
    "product_quantity": 2,
    "product_name": "Nike Air Max 9000",
     "product_shopId ": "{{SHOPID}}"
  }
 }

### delete product in cart
DELETE http://localhost:3001/api/v1/cart/delete
x-api-key : {{APIKEY}}
x-client-id : {{SHOPID}}
authorization : {{ACCESSTOKEN}}
content-type: application/json

{
 "userId": "667", 
 "productId": "66891a418bddb3f5cb89fa8c"
}


### review checkout
POST http://localhost:3001/api/v1/checkout/review
x-api-key : {{APIKEY}}
x-client-id : {{SHOPID2}}
authorization : {{ACCESSTOKEN}}
content-type: application/json

{
  "cartId": "668d3bd10a9c61046dc2fdfa",
  "userId": "667", 
  "shop_order_ids": [
    {
      "shopId": "{{SHOPID}}",
      "shopDiscounts": [],
      "itemProducts": [
        {
          "productId": "66891a418bddb3f5cb89fa8c",
          "price": 150,
          "quantity": 2,
          "name": "Guchi Bag"
        }
      ]
    },
    {
      "shopId": "{{SHOPID2}}",
      "shopDiscounts": [
        {
          "shopId": "{{SHOPID2}}",
          "discountId": "668fecb0052f68d2c7031250",  
          "discountCode": "Birth2024"
        }
      ],
      "itemProducts": [
        {
          "productId": "668fec05052f68d2c703123b",
          "price": 150,
          "quantity": 2,
          "name": "Nike Air Max 9000"
        },
        {
          "productId": "668fec8e052f68d2c7031245",
          "price": 150,
          "quantity": 2,
          "name": "Jordan 1"
        }
      ]
    }
  ]
}
