@ACCESSTOKEN = eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NjdhNjcxMjVjNzY0YzA4YWQ3NzU4ZWEiLCJlbWFpbCI6IjdAZ21haWwuY29tIiwiaWF0IjoxNzIwNTAxOTU4LCJleHAiOjE3MjA1ODgzNTh9.sAYsnfSDqYO6n-ywHew-fJ1BQiz__R67xHALW8cvu4BuNXFg3cBYa0pAevgiOg8LYgvmQRpyzUUbcuqgTw6Rzw3IiadRnct8fgjSMUaFGeeRh_873uHHxUZXxOIC-MVGdjZ2d7SOViaImiN2pBh1j6NykNvGHiZs94dMvYPowqoS0cly7KWRqmEzISglqmmi5PvPcOyKxFK5Mqf_ZtAdW2Xs6n6r8TtN-486wKTqBBB0yg3EEdAPs8YOHB8Kisg3m4n34htGtEH9uuXAqu9FwXCBcRLmme5_ZcEyQsbj-GWjyrPhpS3u60JN-A0RKpgb6ShrujdMcPJKQwNPlPPoLkAzcdvfNER3G4FLQ_OGNl-egxY39RZWbLCLBtk9oLj61GuPWLwFwDwLsIF8DxWpEAK5zSttP5dVggtpBRpNkk_bNreHr8KPt9KrvOlJzG96BKgb3HcrTsLyzd7KymN5yQSSsWo3xgbPqAlLRuK647JDPfd5z-9kJQMKA4wL7Tl1KKJy4d8FZ061JM8rh_LUgl_e00bgBS32atPgc1BWIMFv3AHTjjIXjuRcpob2zFI60TRGKEWVxOfNFEKQTExoEdYWYNmxfAIBn8qhX6Ej6F9oBM0SKOXQ8WQxnfdJjHo-9oHsem_jVR71OXA3iDVEZW6NTyuFTF3Nmj60ox4m_bc
@REFRESHTOKEN = eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NjdhNjcxMjVjNzY0YzA4YWQ3NzU4ZWEiLCJlbWFpbCI6IjdAZ21haWwuY29tIiwiaWF0IjoxNzIwNTAxOTU4LCJleHAiOjE3MjE3MTE1NTh9.PqwF6vLz_GGeLJ6VlEAJGeVQjp0DzANttpAa4zCV6tqpoTKLYgF3HhDvYchteA82brzY2g_1ngXir1Pb2FxDImaAUq7sTa5T48UEsA7DRJJu1baUQmL-jq_UMZcCgmmjBzlQoPqw2xs9TALw1gE-tYp2ifwkY8cap0HpS3Z9wMIN3w0nCNJssI3dnX4ODokEKcRbIdRRiAKP3hkN2TrrITiZkAlf86SYtdNHhEnYZ_aW4ag-mivdx0teTk5uV5DoUkdRdjtUGZ3Gg0LdUD_I059YcR83VmB2QtGAh0hez_nFFHvKuUvPt8A2j4PawSThfFSdPF7Xh9P3MkW2jZ-bzriDUeHbCxErFO1P1QnPHTvNb8hNx9-nQe7sPVpGlkgpY4dypxh_qDJyTQsydqYoh1RFHpKvOGtgRho4wgf-gDI2b-1nWZDRmzNuJzDUN1oqOZ5MPH0fXkGmTqGBgA2UTZ7cm7EzWWfr3KxVN0cUwlwzJ2FN5phJz7mpve-xttpHrH7dtPQ7Zpje80RN0WcCDtJo5u_jgLie_TEBppcn_v81SH_Yu6J86_fLwxJLeHQ51QMyKHveIkp7m14c5WEM8MV4dFdiadXE6hnid1hIYEf2OoffhEEErwIgo0_LeWD0Vtq3WZcQMbEH3JqO-0uE11HIvhKeUwnjH9x8E3SfJvI

@APIKEY = fffbff1907f9fd6c85428a77850851fcdb791963dc660f341d04d7829507e08efcb63ba8037b4e8c6f967e1e5dab3ae81cde008fb88969c0cd18a66a54df8cec

@SHOPID = 667a67125c764c08ad7758ea
### Sign up
x-api-key: {{APIKEY}}
content-type: application/json

{
    "name": "7",
    "email": "7@gmail.com",
    "password": "1234156"
}

### Login
POST http://localhost:3001/api/v1/shop/login
x-api-key: {{APIKEY}}
content-type: application/json

{
    "email": "7@gmail.com",
    "password": "1234156"
}

### logout
POST http://localhost:3001/api/v1/shop/logout
x-api-key : {{APIKEY}}
x-client-id : {{SHOPID}}
authorization : eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJzaG9wSWQiOiI2NjY3YjY0ODRhYTAwMDQ5Yzk4ZTQyYzAiLCJlbWFpbCI6IjRAZ21haWwuY29tIiwiaWF0IjoxNzE4MDcyOTk0LCJleHAiOjE3MTkyODI1OTR9.fAIkPEf3IVInBzBBNBrLOXiqsfgB5HoY6y4Zn8P_NzJNE0gSaACYsF4mcz1trcmo5m8tbbCEj4xzVEau2xZeqg9qx4FBrvPwszCpGNJw0jQ8XKaeYEBIsHRoL3E9uXWW-u84OHDLvbqYGDpfGe66LzAQswHtLqf30VO9fIXN2fcl3PhMrn42LgWODdBvYQlFr9NXbgI3jRXijm_Nk8OuRTdQyD9NORJYB6IRYAEeHSQLdD9bTLurLL8YG2DMny-VVSlNusO4-oR93KD89bXRK-tMo2l2SyBxijHFqbyx74Htn7i8f6XCdpY6MFKf69V-W5MwAdAj_p8E6Kj3cM3oaZgGfRAfZQcdRlRGLHtSJZrUY7nuMw9sECff-dCp2YHuhvPRY0Pz2Zz0xE4W0_79U9pX90zot-GW5iZPSZN4Gq2yzPBO2uVnhnbe_VDerrQt-vOzub9vNNB0-M2MxjRr9cr40dk4ofjR4ZpzNFep0xgSS4jAFfGTv3bZ14UfVMgxhV7ACC9KOHYNID0Ul-G21baO6HtM4CL8CXA9AlaFrrxr8_kJHwPQ8fhE3uHiv_2vdaiU41GsO1A9KJZhsV60rN_1OHuwg2ZXaJZasntxK0JfCc6y6mQO06sIesGoe_z5qftHGelpE-NO0zR2uQ3D4aFkebGWlit0xrO9DZlq5oo


### handle refresh token
POST http://localhost:3001/api/v1/shop/refresh-token
x-api-key : {{APIKEY}}
x-client-id : {{SHOPID}}
authorization : {{ACCESSTOKEN}}
content-type: application/json

{
"refreshToken": "{{REFRESHTOKEN}}"
}

### create product
POST http://localhost:3001/api/v1/product
x-api-key : {{APIKEY}}
x-client-id : {{SHOPID}}
authorization : {{ACCESSTOKEN}}
content-type: application/json

{
  "product_name": "Gucci Bag 1",
  "product_thumbnail": "https://example.com/gucci-bag.jpg 1",
  "product_shop": "{{SHOPID}}",
  "product_price": 120.00,
  "product_quantity": 35,
  "product_type": "clothes",
  "product_description": "Gucci Bag 1",
  "product_attributes": {
    "size": "US 8",
    "color": "black",
    "material": "leather",
    "brand": "Gucci"
  }
}

### get shop draft products
GET http://localhost:3001/api/v1/product/draft/all
x-api-key : {{APIKEY}}
x-client-id : {{SHOPID}}
authorization : {{ACCESSTOKEN}}

### publish product by id
POST http://localhost:3001/api/v1/product/published/66842e21a162a09f714d84b1
x-api-key : {{APIKEY}}
x-client-id : {{SHOPID}}
authorization : {{ACCESSTOKEN}}

### unpublish product by id
POST http://localhost:3001/api/v1/product/unpublished/66842e21a162a09f714d84b1
x-api-key : {{APIKEY}}
x-client-id : {{SHOPID}}
authorization : {{ACCESSTOKEN}}



### get shop published products
GET http://localhost:3001/api/v1/product/published/all
x-api-key : {{APIKEY}}
x-client-id : {{SHOPID}}
authorization : {{ACCESSTOKEN}}

### search product by name,discription
GET http://localhost:3001/api/v1/product/search/nike 90
x-api-key : {{APIKEY}}

### get product by id
GET http://localhost:3001/api/v1/product/66842e21a162a09f714d84b1
x-api-key : {{APIKEY}}

### get all products
GET http://localhost:3001/api/v1/product/all
x-api-key : {{APIKEY}}

### update product by id
PATCH http://localhost:3001/api/v1/product/66842e21a162a09f714d84b1
x-api-key : {{APIKEY}}
x-client-id : {{SHOPID}}
authorization : {{ACCESSTOKEN}}
content-type: application/json

{
  "product_name": "Nike Air Max 9000",
  "product_type": "clothes",
  "product_attributes": {
    "size": "US 9"
  }
}

### create discount
POST http://localhost:3001/api/v1/discount/create
x-api-key : {{APIKEY}}
x-client-id : {{SHOPID}}
authorization : {{ACCESSTOKEN}}
content-type: application/json

{
  "discount_name": "Birth Sale",
  "discount_code": "Birth2024",
  "discount_description": "Birth Sale 2024",
  "discount_shop": "{{SHOPID}}",
  "discount_type": "percentage",
  "discount_value": 20,
  "discount_apply_on": "product",
  "discount_product_ids": ["66891a628bddb3f5cb89fa94","66891a418bddb3f5cb89fa8c"],
  "discount_min_order_value": 100,
  "discount_max_usage": 100,
  "discount_start_date": "2024-07-01",
  "discount_end_date": "2024-07-31"
}

### update discount
PATCH  http://localhost:3001/api/v1/discount/Birth2024
x-api-key : {{APIKEY}}
x-client-id : {{SHOPID}}
authorization : {{ACCESSTOKEN}}
content-type: application/json

{
  "discount_name": "Birth Sale 2024",
  "discount_description": "Birth Sale 2024 Sieu Cap Vip Pro"
}

### get shop discounts
GET http://localhost:3001/api/v1/discount/all
x-api-key : {{APIKEY}}
x-client-id : {{SHOPID}}
authorization : {{ACCESSTOKEN}}

### get product by discount code id
GET http://localhost:3001/api/v1/discount/products
x-api-key : {{APIKEY}}
x-client-id : {{SHOPID}}
authorization : {{ACCESSTOKEN}}
content-type: application/json

{
  "discount_code": "Birth2024",
  "discount_shopId": "{{SHOPID}}"
}

### get amount order
GET http://localhost:3001/api/v1/discount/amount
x-api-key : {{APIKEY}}
x-client-id : {{SHOPID}}
authorization : {{ACCESSTOKEN}}
content-type: application/json

{
  "discount_code": "Birth2024",
  "discount_shopId": "{{SHOPID}}",
  "products": [
    {
      "product_id": "66891a628bddb3f5cb89fa94",
      "product_price": 120,
      "product_quantity": 2
    },
    {
      "product_id": "66891a628bddb3f5cb89fa94",
      "product_price": 120,
      "product_quantity": 1
    }
  ]
}

### add product to cart
POST http://localhost:3001/api/v1/cart/add
x-api-key : {{APIKEY}}
x-client-id : {{SHOPID}}
authorization : {{ACCESSTOKEN}}
content-type: application/json

{"userId": "667", 
 "product": {
    "productId": "66891a418bddb3f5cb89fa8c",
    "product_price": 150,
    "product_quantity": 1,
    "product_name": "Nike Air Max 9000",
     "product_shopId ": "{{SHOPID}}"
  }
 }

### get cart by user id
GET http://localhost:3001/api/v1/cart/
x-api-key : {{APIKEY}}
x-client-id : {{SHOPID}}
authorization : {{ACCESSTOKEN}}
content-type: application/json

{"userId": "667"}

### update product in cart
PATCH http://localhost:3001/api/v1/cart/update
x-api-key : {{APIKEY}}
x-client-id : {{SHOPID}}
authorization : {{ACCESSTOKEN}}
content-type: application/json

{"userId": "667", 
 "product": {
    "productId": "66891a418bddb3f5cb89fa8c",
    "product_price": 150,
    "product_quantity": 2,
    "product_name": "Nike Air Max 9000",
     "product_shopId ": "{{SHOPID}}"
  }
 }

### delete product in cart
DELETE http://localhost:3001/api/v1/cart/delete
x-api-key : {{APIKEY}}
x-client-id : {{SHOPID}}
authorization : {{ACCESSTOKEN}}
content-type: application/json

{"userId": "667", 
 "productId": "66891a418bddb3f5cb89fa8c"
 }